### ISSUE TITLE
Idea for tps boost. 

### ISSUE THREAD

**Issue by eremenkod** [YatopiaMC/Yatopia#413]
**Describe what do you want us to implement**
Im want see a Fabric mod like Lithuim. 

**Is your feature request related to a problem**

No. 
**Additional context**

Link 
https://www.curseforge.com/minecraft/mc-mods/phosphor

**Comment by ahdg6** [comment]
as far as I am concerned,Yatopia has a Upstream called Tunity,which has the best light engine for minecraft,so phosphor isn't needed.

**Comment by MrTechyyy** [comment]
>Asks for Lithium (Yatopia already includes some patches with Lithium)
>Links Phosphor

**Comment by Hellohi3654** [comment]
and before you link hydrogen yatopia also uses some of that as well

**Comment by XjCyan1de** [comment]
Done. https://github.com/YatopiaMC/barium-fabric

**Comment by ishland** [comment]
Closing as invalid. 
If you have further questions, please join our [discord server](https://discord.gg/YatopiaMC)
